name: lin gcc_arm64

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gcc-aarch64
      run: |
        sudo apt-get update
        sudo apt-get install -y -q gcc-aarch64-linux-gnu
        sudo apt-get install -y -q binfmt-support qemu qemu-user-static
    - name: Get Sources
      uses: actions/checkout@v4
    - name: Build and Test
      run: |
        wget -q https://musl.cc/aarch64-linux-musl-cross.tgz
        tar -xzf aarch64-linux-musl-cross.tgz      
        ./aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc --version
        sudo cp -r ./aarch64-linux-musl-cross/aarch64-linux-musl/lib/* /lib/
        wget -q https://gamma.hdfgroup.org/ftp/pub/outgoing/h4map/src/h4map.tar.gz
        tar -xzf h4map.tar.gz
        cd h4map/jpeg-6b
        ./configure CC=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc AR=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar
        make
        sudo make install-lib
        cd ../..
        git clone https://github.com/madler/zlib
        cd zlib
        CC=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc AR=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar ./configure
        make
        sudo make install
        cd ..
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc -DCMAKE_AR=/home/runner/work/hdf4/hdf4/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar -DCMAKE_SYSTEM_PROCESSOR=aarch64-linux-musl -DBUILD_SHARED_LIBS:BOOL=OFF -DHDF4_BUILD_FORTRAN:BOOL=OFF ..        
        make
        make test
