name: mac14 clang17 f

on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:
    name: "mac14 clang17 f"
    runs-on: macos-14
    steps:
    - name: Install Dependencies
      run: |
        brew install  jpeg llvm libaec ninja
        brew reinstall gfortran
    - name: Get Sources
      uses: actions/checkout@v4.1.1
    - name: Test HDF4
      run: |
        export PATH=/opt/homebrew/opt/llvm/bin:$PATH
        export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
        export CC=$(brew --prefix llvm)/bin/clang
        export FC=/opt/homebrew/bin/gfortran
        mkdir build
        cd build
        cmake -G Ninja \
        -D BUILD_SHARED_LIBS=OFF \
        -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
        -D HDF4_BUILD_FORTRAN:BOOL=ON \
        -D SITE:STRING=f.clang17.mac14 \
        ..
        ctest -D Experimental
      shell: bash
