name: mac14 f j cd

on:
  workflow_dispatch:
  push:
    branches: [ master- ]
jobs:
  build:
    name: mac14 f j cd
    runs-on: macos-14
    steps:
    - name: Install Dependencies (macOS)
      run: |
        brew install ninja libaec jpeg
        brew reinstall gfortran
    - name: Get Sources
      uses: actions/checkout@v4.1.1

    - name: Test
      run: |
        export FC=/opt/homebrew/bin/gfortran
        mkdir build
        cd build
        cmake -G Ninja \
        -D HDF4_BUILD_FORTRAN:BOOL=ON \
        -D BUILD_SHARED_LIBS=ON \
        -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
        -D HDF4_BUILD_JAVA=ON \
        -D SITE:STRING=j.f.mac14 \
        ..
        ctest -D Experimental

