name: mac14 auto clang17 f j sh

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: mac14 auto clang17 f j sh
    runs-on: macos-14
    steps:
      - name: Install Dependencies
        run: |
          brew install autoconf automake jpeg libaec libtool llvm
          brew reinstall gfortran
      - name: Get Sources
        uses: actions/checkout@v4.1.1
      - name: Test HDF4
        run: |
          export PATH=/opt/homebrew/opt/llvm/bin:$PATH
          export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
          export CC=$(brew --prefix llvm)/bin/clang
          export FC=/opt/homebrew/bin/gfortran
          echo $FC
          brew info jpeg
          ./autogen.sh
          ./configure --prefix=/tmp --enable-fortran --enable-java --enable-shared --with-jpeg=/opt/homebrew/opt/jpeg
          make
          make check
